JafriCode/urls.py
from django.contrib import admin
from django.urls import path, include
import users, main_app
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('main_app.urls')),
    path('courses/', include('courses.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('all_users/', views.all_users, name='all_users'), 
    path('all_students/', views.all_students, name='all_students'),
    path('enrollment/', views.enrollment, name='enrollment'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('blog/', views.blog, name='blog'),
    path('blog/category/<int:category_id>/', views.category_posts, name='category_posts'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('Terms & Conditions/', views.terms, name='terms'),
    path('Privacy Policy/', views.privacy, name='privacy'),
    path('JafriCode Intro/', views.jc_intro, name='jc_intro'),
    path('About Instructor/', views.about_inst, name='about_inst'),
    path('single_page_blog/<int:post_id>/', views.single_page_blog, name='single_page_blog'),

]  

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('register/', views.registration_view, name='register'),
    # path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('setting/', views.setting, name='setting'),
    path('my_courses/', views.my_courses, name='my_courses'),
    path('student_lessons/', views.student_lessons, name='student_lessons'),
]

main_app/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()
    SEO_description = models.CharField(blank=True, null=True,max_length=255)  # Added SEO description field
    categories = models.ManyToManyField(Category)
    thumbnail = models.ImageField(upload_to='post_thumbnails/', null=True, blank=True)

    # Published date defaults to the current date and time when the post is published
    published_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"   
class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Reply by {self.name} on {self.comment.post}"

class Subscriber(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

main_app/forms.py
from django import forms
from .models import Subscriber, Comment, Reply
class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'comment']

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply']

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data['email']
        if Subscriber.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already subscribed.")
        return email

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post,Category
from django.db.models import Count, Sum
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate
from django.core.mail import send_mail
from .forms import ContactForm, SubscriberForm
from django.contrib import messages
from courses.models import Category as CourseCategory
from courses.models import Cart, Enrollment, Course
from django.contrib.auth.decorators import login_required
from main_app.models import Post, Category,Comment
import random
from courses.views import get_cart_items  # Import the function from the courses app
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import JsonResponse
from .models import Subscriber
from .forms import CommentForm, ReplyForm
from django.http import HttpResponseRedirect


def fetch_categories():
    return CourseCategory.objects.all()

def handle_login_registration(request):
    registration_form = UserCreationForm()
    login_form = AuthenticationForm()

    if request.method == 'POST':
        if 'register' in request.POST:
            registration_form = UserCreationForm(request.POST)
            if registration_form.is_valid():
                registration_form.save()
                username = registration_form.cleaned_data.get('username')
                password = registration_form.cleaned_data.get('password1')
                user = authenticate(username=username, password=password)
                login(request, user)
                return redirect('homepage')  # Redirect to home page after successful registration
        elif 'login' in request.POST:
            login_form = AuthenticationForm(data=request.POST)
            if login_form.is_valid():
                username = login_form.cleaned_data.get('username')
                password = login_form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('homepage')  # Redirect to home page after successful login

    return registration_form, login_form
    
def fetch_random_categories():
    # Fetch all categories
    all_categories = CourseCategory.objects.all()
    # Shuffle the categories randomly
    random_categories = random.sample(list(all_categories), min(len(all_categories), 8))
    return random_categories
def homepage(request):
    courses = Course.objects.all()
    blog_posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:3]
    blog_categories = Category.objects.all()  # Query all categories
    random_categories = fetch_random_categories()

    categories = fetch_categories()
    
    # Call handle_login_registration function to handle registration
    forms_or_redirect = handle_login_registration(request)
    
    try:
        # Unpack the returned forms
        registration_form, login_form = forms_or_redirect if len(forms_or_redirect) == 2 else (forms_or_redirect[0], None)
    except TypeError:  # Handle TypeError if redirect response is returned
        return forms_or_redirect
    cart_items, cart_courses, total_courses = get_cart_items(request)

    context = {
        'registration_form': registration_form,
        'login_form': login_form,
        'categories': categories,
        'courses': courses,
        'blog_posts':blog_posts,
        'blog_categories':blog_categories,
        'random_categories':random_categories,
        'cart_courses': cart_courses,  # Pass the cart courses to the template context
        'cart_items': cart_items,
        'total_courses':total_courses,
    }
    return render(request, 'main_app/homepage.html', context)

def dashboard(request):
    return render(request, 'main_app/dashboard.html')

def all_users(request):
    return render(request, 'main_app/all_users.html')

def all_students(request):
    # Retrieve all enrollments
    enrollments = Enrollment.objects.select_related('student', 'course').all()

    # Prepare data to pass to the template
    student_data = []
    for enrollment in enrollments:
        # Extract information for each enrollment
        student_name = f"{enrollment.student.first_name} {enrollment.student.last_name}"
        email = enrollment.student.email
        course_title = enrollment.course.title
        offer_price = enrollment.course.offer_price
        completion_status = "Completed" if enrollment.completion_status else "Incomplete"
        enrollment_date = enrollment.enrollment_date
        country = enrollment.student.profile.country

        # Append data to the list
        student_data.append({
            'student_name': student_name,
            'email': email,
            'course_title': course_title,
            'offer_price': offer_price,
            'completion_status': completion_status,
            'enrollment_date': enrollment_date,
            'country': country,
        })

    # Pass the data to the template for rendering
    context = {
        'student_data': student_data,
    }
    return render(request, 'main_app/all_students.html', context)

def enrollment(request):
    return render(request, 'main_app/enrollment.html')

@login_required
def cart(request):
    cart_items, cart_courses, total_courses = get_cart_items(request)
    # Fetch cart items for the logged-in user
    user_cart_items = Cart.objects.filter(user=request.user).prefetch_related('courses')

    # Calculate subtotal and total using Django aggregation
    subtotal = sum(course.offer_price for course in cart_items)  # Sum offer prices of all courses
    total = subtotal  # You can apply any discounts or taxes here if needed

    categories = fetch_categories()
    context = {
        'categories': categories,
        'subtotal': subtotal,
        'total': total,
        'user_cart_items': user_cart_items,
        'cart_courses': cart_courses,
        'total_courses': total_courses,
        'cart_items': cart_items,

    }
    return render(request, 'main_app/cart.html', context)

@login_required
def checkout(request):
    cart_items, cart_courses, total_courses = get_cart_items(request)
    # Fetch cart items for the logged-in user
    user_cart_items = Cart.objects.filter(user=request.user).prefetch_related('courses')

    # Calculate subtotal and total
    subtotal = sum(item.courses.aggregate(Sum('offer_price'))['offer_price__sum'] or 0 for item in user_cart_items)
    total = subtotal  # Add any additional charges or taxes here

    categories = fetch_categories()
    context = {
        'categories': categories,
        'user_cart_items': user_cart_items,
        'subtotal': subtotal,
        'total': total,
        'cart_courses': cart_courses,  # Pass the cart courses to the template context
        'cart_items': cart_items,
        'total_courses':total_courses,
    }
    return render(request, 'main_app/checkout.html', context)

def blog(request):
    cart_items, cart_courses, total_courses = get_cart_items(request)

    categories = fetch_categories()
    posts = Post.objects.all()
    # Fetch the first 4 recent posts ordered by published date
    recent_posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:4]

    blog_categories = Category.objects.all()  # Query all categories
    categories_with_posts = Category.objects.annotate(num_posts=Count('post')).filter(num_posts__gt=0)
    # Call handle_login_registration function to handle registration
    forms_or_redirect = handle_login_registration(request)
    
    try:
        # Unpack the returned forms
        registration_form, login_form = forms_or_redirect if len(forms_or_redirect) == 2 else (forms_or_redirect[0], None)
    except TypeError:  # Handle TypeError if redirect response is returned
        return forms_or_redirect
    
    query = request.GET.get('q')
    if query:
        # Filter posts by title (exact match)
        posts = Post.objects.filter(title__icontains=query)
    else:
        posts = Post.objects.all()

   # Pagination
    paginator = Paginator(posts, 4)  # 10 courses per page
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results
        posts = paginator.page(paginator.num_pages)   
    context = {
        'posts': posts, 
        'categories': blog_categories, 
        'recent_posts': recent_posts,
        'categories': categories, 
        'categories_with_posts':categories_with_posts,
        'registration_form': registration_form,
        'login_form': login_form,
        'cart_courses': cart_courses,  # Pass the cart courses to the template context
        'cart_items': cart_items,
        'query':query,
        'total_courses':total_courses,
        }  
    return render(request, 'main_app/blog.html', context)

def category_posts(request, category_id):
    cart_items, cart_courses, total_courses = get_cart_items(request)
    categories = fetch_categories()
    category = get_object_or_404(Category, id=category_id)
    posts = category.post_set.all()
    categories_with_posts = Category.objects.annotate(num_posts=Count('post')).filter(num_posts__gt=0)
    # Fetch the first 4 recent posts ordered by published date
    recent_posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:4]
    # Call handle_login_registration function to handle registration
    forms_or_redirect = handle_login_registration(request)
    
    try:
        # Unpack the returned forms

main_app/templates/main_app/about_instructor.html
{% extends 'main_app/base.html' %}

{% block content %}
{% load static %}
<div class="container mt-3">
    <div class="row">
    
            <div class="tab-content" id="v-pills-tabContent">
                <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                
                    <h1> Meet with Faisal Zamir (JafriCode CEO):</h1>

                    <p>Faisal Zamir is a Udmey-rated instructor from Pakistan, having millions of students enrolled in different courses like Python, Javascript, web designing, etc.</p>
                    <img src="{% static 'assets/img/faisal zamir.png' %}" class="img-fluid" alt="Description of your image">

                    <p>He created different platforms where you can learn Python in text form, there are beneficial articles written on his blog as PythonProSupport. If you are interested in his teaching style, online live webinar, make money courses, etc you can follow him on YouTube also.</p>
                    <h2>Uniqueness in My Teaching:​</h2>
                    <p>Our effort is to provide content in a unique style that helps students understand any difficult topic more simply:</p>
                    <h3>Some of our unique characteristics:</h3>
                    <ul>
                        <li>Course topics management</li>
                        <li>Course breaking into proper outlines</li>
                        <li>Example to Clear Topics</li>
                        <li>Assignments</li>
                        <li>Exercises and Solution</li>
                        <li>Quiz</li>
                        <li>Good video and audio quality</li>
                        <li>Source code (with every course)</li>
                        <li>PPT Slides</li>
                    </ul>
                    
                    <h3>I want to share something with my students.</h3>
                    <ul>
                        <li>Don't waste your time</li>
                        <li>Be a hard worker</li>
                        <li>Always be positive</li>
                        <li>You should learn any skill if you want to become great</li>
                        <li>Your skills can help you in every field of life</li>
                        <li>I did not mean to always open the laptop and read a book; I want to say that learn any skill and try to solve people's problems</li>
                        <li>You can do great things!</li>
                    </ul>
                    
                </div>
               
            </div>
        </div>
    </div>

    {% endblock %}

main_app/templates/main_app/blog_sidebar.html
<div class="">
    <div class="border rounded mb-6">
        <div class="border rounded mb-6">
            <form method="GET" action="{% url 'blog' %}">
                <div class="input-group">
                    <input name="q" class="form-control form-control-sm border-0 pe-0" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-sm my-2 my-sm-0 text-secondary icon-uxs" type="submit">
                            <!-- Icon -->
                            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M8.80758 0C3.95121 0 0 3.95121 0 8.80758C0 13.6642 3.95121 17.6152 8.80758 17.6152C13.6642 17.6152 17.6152 13.6642 17.6152 8.80758C17.6152 3.95121 13.6642 0 8.80758 0ZM8.80758 15.9892C4.8477 15.9892 1.62602 12.7675 1.62602 8.80762C1.62602 4.84773 4.8477 1.62602 8.80758 1.62602C12.7675 1.62602 15.9891 4.8477 15.9891 8.80758C15.9891 12.7675 12.7675 15.9892 8.80758 15.9892Z" fill="currentColor"/>
                                <path d="M19.762 18.6121L15.1007 13.9509C14.7831 13.6332 14.2687 13.6332 13.9511 13.9509C13.6335 14.2682 13.6335 14.7831 13.9511 15.1005L18.6124 19.7617C18.7712 19.9205 18.9791 19.9999 19.1872 19.9999C19.395 19.9999 19.6032 19.9205 19.762 19.7617C20.0796 19.4444 20.0796 18.9295 19.762 18.6121Z" fill="currentColor"/>
                            </svg>
        
                        </button>
                    </div>
                </div>
            </form>
        </div>
        

    <div class="border rounded mb-6 p-5 py-md-6 ps-md-6 pe-md-4">
        <h4 class="mb-5">Category</h4>
        <div class="nav flex-column nav-vertical">
            {% for category in categories_with_posts %}
            <a href="{% url 'category_posts' category.id %}" class="nav-link py-2">{{ category.name }} ({{category.num_posts}}) </a>
            {% endfor %}

        </div>
    </div>

    <div class="border rounded mb-6 p-5 py-md-6 ps-md-6 pe-md-4">
        <h4 class="mb-5">Recent Posts</h4>
        <ul class="list-unstyled mb-0">
            {% for post in recent_posts %}

            <li class="media mb-6 d-flex">
                <a href="#" class="mw-70p d-block me-5">
                    <img src="{{post.thumbnail.url}}" alt="..." class="avatar-img rounded-lg h-70p o-f-c">
                </a>
                <div class="media-body flex-shrink-1">
                    <a href="#" class="d-block">
                        <h6 class="line-clamp-2 mb-1 fw-normal">{{post.title}}</h6>
                    </a>
                    <span>{{post.published_date}}</span>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>


</div>

main_app/templates/main_app/single.html
{% extends 'main_app/base.html' %}

{% block content %}
{% load static %}
<style>
    .comment-box {
      border: 1px solid #ddd;
      padding: 10px;
      margin-bottom: 20px;
    }
    .reply-form {
      display: none;
    }
  </style>
<div class="container py-8 pt-lg-11">
    <div class="row">
        <div class="col-xl-8 mx-auto">
          <!-- Display post title -->
            <h1>{{ post.title }}</h1>
            <p> Published: <b>{{ post.published_date }}</b> Last Updated: <b> {{ post.updated_date }}</b>
               <p>
                {% for category in post.categories.all %}
                Category: <b>{{ category.name }}</b>
            {% endfor %}
               </p>
                   
               
            </p>

            <p>{{ post.content|safe }}</p>

        </div>
    </div>
</div>

<div class="mb-8 sk-thumbnail img-ratio-7">
    <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}" class="img-fluid">
</div>

<div class="container">
    <div class="row mb-8 mb-md-12">
        <div class="col-xl-8 mx-auto">
            
            <div class="row mb-6 mb-md-10 align-items-center">
                <div class="col-md-4 mb-5 mb-md-2">
                    
                    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" class="text-teal fw-medium d-flex align-items-center">
                        
                        <!-- Icon -->
                        <i class="fas fa-share"></i>
                        <span class="ms-3"> Share on Facebook</span>
                    </a>
                </div>

                <div class="col-md-8">
                </div>
            </div>

       
            <div class="container mt-5">
                <!-- Comment Section -->
                <div id="comments">
                    {% for comment in comments %}
                    <!-- Existing Comments -->
                    <div class="comment-box">
                        <img src="{% static 'assets/img/JafriCode Transparent.png' %}" alt="Profile Picture" style="width: 50px; height: 50px; border-radius: 50%; float: left; margin-right: 10px;">
                        <h5>{{ comment.name }}</h5>
                        <p>{{ comment.comment }}</p>
                        <button class="btn btn-sm btn-primary reply-btn">Reply</button>
                        <!-- Reply Form (Hidden by default) -->
                        <div class="reply-form mt-3" style="display: none;">
                            <form method="post" id="replyForm">
                                {% csrf_token %}
                                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                                <div class="form-group">
                                    <label for="reply-comment">Comment:</label>
                                    <textarea class="form-control" id="reply-comment" name="{{reply_form.reply.name}}" rows="3" placeholder="Write your reply here"></textarea>
                                </div>
                                <button type="submit" name="replyForm" class="btn btn-sm btn-primary">Submit</button>
                            </form>
                        </div>
                        <!-- Existing Replies -->
                        {% for reply in comment.reply_set.all %}
                        <div class="reply-box mt-3">
                            <img src="{% static 'assets/img/faisal zamir instructor.png' %}" alt="Profile Picture" style="width: 50px; height: 50px; border-radius: 50%; float: left; margin-right: 10px;">
                            <h6>{{ reply.name }}</h6>
                            <p>{{ reply.reply }}</p>
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
                <!-- Comment Form -->
                <div class="mt-5">
                    <h4>Leave a Comment</h4>
                    <form id="commentForm" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" name="{{ comment_form.name.name }}" class="form-control" id="name" placeholder="Enter your name">
                        </div>
                        <div class="form-group">
                            <label for="comment">Comment:</label>
                            <textarea class="form-control" name="{{ comment_form.comment.name }}" rows="5" id="comment" placeholder="Write your comment here"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary" name="commentForm">Submit</button>
                    </form>
                </div>
            </div>
            
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script>
                $(document).ready(function(){
                    // Show reply form when reply button is clicked
                    $(document).on("click", ".reply-btn", function(){
                        $(this).siblings(".reply-form").slideToggle();
                    });
                });
            </script>
            
            
            
              
        
                
            
            </div>
        </div>
    </div>

    <div class="row align-items-end mb-4 mb-md-7">
        <div class="col-md mb-4 mb-md-0">
            <h1 class="mb-1">Latest News</h1>
            <p class="font-size-lg mb-0 text-capitalize">Discover your perfect program in our courses.</p>
        </div>
        <div class="col-md-auto">
            <a href="{% url 'blog' %}" class="d-flex align-items-center fw-medium">
                Browse All
                <div class="ms-2 d-flex">
                    <!-- Icon -->
                    <svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M7.7779 4.6098L3.32777 0.159755C3.22485 0.0567475 3.08745 0 2.94095 0C2.79445 0 2.65705 0.0567475 2.55412 0.159755L2.2264 0.487394C2.01315 0.700889 2.01315 1.04788 2.2264 1.26105L5.96328 4.99793L2.22225 8.73895C2.11933 8.84196 2.0625 8.97928 2.0625 9.1257C2.0625 9.27228 2.11933 9.4096 2.22225 9.51269L2.54998 9.84025C2.65298 9.94325 2.7903 10 2.9368 10C3.0833 10 3.2207 9.94325 3.32363 9.84025L7.7779 5.38614C7.88107 5.2828 7.93774 5.14484 7.93741 4.99817C7.93774 4.85094 7.88107 4.71305 7.7779 4.6098Z" fill="currentColor"/>
                    </svg>

                </div>
            </a>
        </div>
    </div>

    <div class="row row-cols-md-2 row-cols-lg-3 mb-8 mb-md-11">
        {%  for post in recent_posts %}
        <div class="col-md mb-5 mb-lg-0">
            <!-- Card -->
            <div class="card border shadow p-2 lift sk-fade">
                <!-- Image -->
                <div class="card-zoom position-relative">
                    <a href="{% url 'single_page_blog' post.id %}" class="card-img d-block sk-thumbnail img-ratio-3"><img class="rounded shadow-light-lg img-fluid" src="{{ post.thumbnail.url }}" alt="..."></a>

                    <a href="{% url 'category_posts' post.categories.first.id %}" class="badge sk-fade-bottom badge-lg badge-purple badge-pill badge-float bottom-0 left-0 mb-4 ms-4 px-5 me-4">
                        <span class="text-white fw-normal font-size-sm">
                            {{ post.categories.first }}
                        </span>
                    </a>
                </div>

                <!-- Footer -->
                <div class="card-footer px-2 pb-0 pt-4">
                    <ul class="nav mx-n3 mb-3">
                        <li class="nav-item px-3">
                            <a href="#" class="d-flex align-items-center text-gray-800">
                                <div class="me-3 d-flex">
                                    <!-- Icon -->
                                    <svg width="15" height="15" viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M13.8102 9.52183C13.313 9.08501 12.7102 8.70758 12.0181 8.40008C11.7223 8.2687 11.3761 8.40191 11.2447 8.69762C11.1134 8.99334 11.2466 9.33952 11.5423 9.47102C12.1258 9.73034 12.6287 10.0436 13.0367 10.4021C13.5396 10.8441 13.8281 11.484 13.8281 12.1582V13.2422C13.8281 13.5653 13.5653 13.8281 13.2422 13.8281H1.75781C1.43475 13.8281 1.17188 13.5653 1.17188 13.2422V12.1582C1.17188 11.484 1.46038 10.8441 1.96335 10.4021C2.55535 9.88186 4.2802 8.67188 7.5 8.67188C9.89079 8.67188 11.8359 6.72672 11.8359 4.33594C11.8359 1.94515 9.89079 0 7.5 0C5.10921 0 3.16406 1.94515 3.16406 4.33594C3.16406 5.7336 3.82896 6.97872 4.85893 7.77214C2.97432 8.18642 1.80199 8.98384 1.18984 9.52183C0.433731 10.1862 0 11.147 0 12.1582V13.2422C0 14.2115 0.788498 15 1.75781 15H13.2422C14.2115 15 15 14.2115 15 13.2422V12.1582C15 11.147 14.5663 10.1862 13.8102 9.52183ZM4.33594 4.33594C4.33594 2.59129 5.75535 1.17188 7.5 1.17188C9.24465 1.17188 10.6641 2.59129 10.6641 4.33594C10.6641 6.08059 9.24465 7.5 7.5 7.5C5.75535 7.5 4.33594 6.08059 4.33594 4.33594Z" fill="currentColor"/>
                                    </svg>

                                </div>
                                <div class="font-size-sm">Faisal Zamir</div>
                            </a>
                        </li>
                        <li class="nav-item px-3">
                            <a href="#" class="d-flex align-items-center text-gray-800">
                                <div class="me-2 d-flex">
                                    <!-- Icon -->
                                    <svg width="15" height="15" viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M13.0664 1.17188H11.7188V0.46875C11.7188 0.209883 11.5089 0 11.25 0C10.9911 0 10.7812 0.209883 10.7812 0.46875V1.17188H4.21875V0.46875C4.21875 0.209883 4.0089 0 3.75 0C3.4911 0 3.28125 0.209883 3.28125 0.46875V1.17188H1.93359C0.867393 1.17188 0 2.03927 0 3.10547V13.0664C0 14.1326 0.867393 15 1.93359 15H13.0664C14.1326 15 15 14.1326 15 13.0664V3.10547C15 2.03927 14.1326 1.17188 13.0664 1.17188ZM1.93359 2.10938H3.28125V2.57812C3.28125 2.83699 3.4911 3.04688 3.75 3.04688C4.0089 3.04688 4.21875 2.83699 4.21875 2.57812V2.10938H10.7812V2.57812C10.7812 2.83699 10.9911 3.04688 11.25 3.04688C11.5089 3.04688 11.7188 2.83699 11.7188 2.57812V2.10938H13.0664C13.6157 2.10938 14.0625 2.55621 14.0625 3.10547V4.21875H0.9375V3.10547C0.9375 2.55621 1.38434 2.10938 1.93359 2.10938ZM13.0664 14.0625H1.93359C1.38434 14.0625 0.9375 13.6157 0.9375 13.0664V5.15625H14.0625V13.0664C14.0625 13.6157 13.6157 14.0625 13.0664 14.0625Z" fill="currentColor"/>
                                    </svg>

                                </div>
                                <div class="font-size-sm">{{ post.published_date }}</div>
                            </a>
                        </li>
                    </ul>

                    <!-- Heading -->
                    <a href="{% url 'single_page_blog' post.id %}" class="d-block"><h5 class="line-clamp-2 h-48 h-lg-52">{{ post.title }}</h5></a>
                </div>
            </div>
        </div>
        {% endfor %}
    
    </div>
</div>

    {% endblock %}